### ISSUE TITLE
Could you provide the code

### ISSUE THREAD

**Issue by agryji08** [panpanfei/Biomass-Prediction-with-3D-Point-Clouds-from-LiDAR#1]
I read your paper and I am interested in it. Then I find your git. But there is no code there. could you provide the code.

**Comment by panpanfei** [comment]
Hi, apologize for not checking GitHub regularly. I have already left CSIRO and uploaded all project-related stuff to CSIRO. I am afraid that I do not have the authority to release the code on my private webpage.
